title: Makers All Toolkit
author: Anders Schneiderman
email: your-email@domain.com
description:  Makers All Toolkit

# Menu data for sitewide navigation
navigation_links:
  - name: About
    link: 'about/'
  - name: Tools
    link: '/tools/'
  - name: Training & Opportunities
    link: '/jobs-training'
  - name: Rethinking Makers
    link: '/rethink/'
  # - name: Overview
    # link: '/pages/10-intro/00-index.html'
  # - name: Makers All
    # link: 'https://makersall.org'


# google_analytics: UA-139179554-1